### ISSUE TITLE
Casting on generated java seems to be broken

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-codegen#10]
I've the interface:

    @VertxGen
    public interface Cookie {
      boolean isSigned();
    }

And another:

    @VertxGen
    public interface Request {
      List<Cookie> cookies();
      Cookie getCookie(String name);
    }

This generated broken code:

[ERROR] Request.java: incompatible types: java.util.Set<io.vertx.ext.yoke.http.Cookie> cannot be converted to java.util.Set<io.vertx.java.ext.yoke.http.Cookie>

The generated code (this part is good):

    public Cookie getCookie(String name) {
      Cookie ret= Cookie.newInstance(this.delegate.getCookie(name));
      return ret;
    }

This isn't!

    public List<Cookie> getAllCookies(String name) {
      List<Cookie> ret = this.delegate.getAllCookies(name);
      return ret;
    }

**Comment by vietj** [comment]
Hi, can you tell us which code generator produced this code ? Groovy ? Proxy service ? RxJava ?

**Comment by pmlopes** [comment]
it was groovy, but this was like 6months ago... probably not applicable anymore.

**Comment by vietj** [comment]
thanks
