### ISSUE TITLE
Missing @Nullable-information for annotated generics

### ISSUE THREAD

**Issue by codepitbull** [vert-x3/vertx-codegen#111]
While reimplementing the Nullable-code for Scala I came around the following issue:
NullableTCK has the following method:
void methodWithNullableListByteHandlerAsyncResult(boolean notNull, Handler<AsyncResult<@Nullable List<Byte>>> handler);

In my old implementation I scattered the code with null-checks which I currently try to replace with scala-Options.
My problem is that I can't get a hold of the Nullable-information.
Traversing the TypeInfo from Handler down to the actually Nullable List never shows anything to be nullable.

**Comment by vietj** [comment]
fixed
