### ISSUE TITLE
Allow custom annotations on DataObject properties

### ISSUE THREAD

**Issue by Cafeinoman** [vert-x3/vertx-codegen#115]
Can you consider to allow access to custom annotation on DataObject properties ? One simple use case is a Date annotation that can be use to specify a datepicker field while generating javascript UI...

**Comment by vietj** [comment]
how would these be available ?

you want to generate some UI template from data objects ?

**Comment by Cafeinoman** [comment]
Yep, I'm working on a Vertx based framework which, among other thing, should generate default javascript ui from the api.
It can be available, I think, by creating an AnnotationTypeInfo from AnnotationMirror, and add a (potentially empty) List<AnnotationTypeInfo> to the PropertyInfo class. I'm working on a PR, the only problematic thing actually is to handle properly the annotations values. It's possible that it need some additional classes...

**Comment by vietj** [comment]
how about exposing the related TypeElement of the data object ?

**Comment by Cafeinoman** [comment]
If you think to directly expose it as a template variable, I think it's a bad idea. You can't get the annotations with Element#getAnnotation, as the custom annotation may be not in the classpath at generation time. And it need too much code in the template itself to find if the property is annotated, with which annotation, and to find the annotations values if exists.
I think the best option is to add a DataObjectModel#processAnnotation, call it in the DataObjectModel#processMethods to build a Map<String,List<AnnotationTypeInfo>> and pass the list to each PropertyInfo constructor.

**Comment by vietj** [comment]
@Cafeinoman is that something you can contribute ?

**Comment by Cafeinoman** [comment]
Work on it yes. The only problem is for the values of the annotation, but I think the PR will come in one week maybe. If can't handle it, I'll come back to ask help.
