### ISSUE TITLE
Regression in Rx-ification

### ISSUE THREAD

**Issue by jponge** [vert-x3/vertx-codegen#139]
Exposed with the guide for Java devs and the Rx-ification of the JWT auth API, see https://github.com/vert-x3/vertx-auth/issues/155

**Comment by pmlopes** [comment]
This is not a code gen issue. Code gen does not allow overload with json object and data object, so we need to mark one as gen ignore given that data object brings type safety and better docs I choose to ignore the json one. I also documented it on the breaking changes...

**Comment by jponge** [comment]
👍
