### ISSUE TITLE
VertxProxyHandler fails when replying with DataObject

### ISSUE THREAD

**Issue by tanneess** [vert-x3/vertx-codegen#145]
Generated VertxProxyHandler and VertxEBProxy do not require MessageCodecs for DataObjects that are passed as inputs. However sending a DataObject reply produces the following error: java.lang.IllegalArgumentException: No message codec for type.

This is because inputs are serialized/unserialized from Json while the reply is sent untouched through the event bus.

In a sense MessageCodec behaviour is backed in the VertxEBProxy and VertxProxyHandler for input and not outputs. 

This is inconsistent and seems to me like a bug. This does not match what is documented here http://vertx.io/docs/vertx-service-proxy/java/#_restrictions_for_service_interface, which states that a DataObject should be ok for input as well as reply.

**Comment by vietj** [comment]
can you show a reproducer ?

**Comment by vietj** [comment]
do you mean a reply with a bare EventBus message consumer ?

**Comment by vietj** [comment]
can you open this issue in the service-proxy repo instead of this one ?

**Comment by tanneess** [comment]
Voilà here it is: https://github.com/vert-x3/vertx-service-proxy/issues/64.
