### ISSUE TITLE
Consider generating toJson and Json constructor for DataObject classes

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-codegen#15]

**Comment by vietj** [comment]
implemented

**Comment by msavy** [comment]
As I understand from the docs you've added, this won't work for ancestor properties.

In my case, I'm wrapping `serializable` JavaBeans (they're passed into apiman from the core) into a Vertx specific version that is annotated with `@DataObject`. They're essentially empty, save for the constructors

E.g. Provided interface

```
class ServiceRequest {
   Map<> headers = ...;
   String endpoint = ...;
}
```

Wrapped interface

```
@DataObject
class VertxServiceRequest extends ServiceRequest {
   public(JsonObject fromJson) {
      ... 
   }

   public() {
     ...
   }
}
```

In this case the new functionality wouldn't work, as `headers` and `endpoint` would not be visible?

**Comment by vietj** [comment]
The idea of this behavior is that the super class should handle conversion and should use its own converter, for instance:

```
@DataObject
class A {
  public A(JsonObject json) {
    AConvert.fromJson(json, this)
  }
}
```

```
@DataObject
class B extends A {
  public B(JsonObject json) {
    super(json);
    BConverter.fromJson(json, this);
  }
}
```

Same for `toJson()` .

So I think that if you follow this pattern it should work.

**Comment by msavy** [comment]
The problem is that I can’t label `class A` as @DataObject, because it comes from a dependency/library (apiman-core), and cannot modify the class definition (i.e. I can’t add /any/ annotations onto it); hence extending it to create `class VertxB extends UnmodifiableA`, which I *can* annotate.

Could not a reasonable option would be to have a variant which will traverse all parents (i.e. like JSON.encode from Jackson)?

Also, would it not be reasonable to assume that anything that implements Serializable is essentially a `@DataObject`?

**Comment by vietj** [comment]
- it seems reasonnable we could have a annotation config that controls this behavior and have all properties in the converter like @DataObject(generateAll=true)
- do you mean that something that is Serializable could be marshalled to byte[] ?

keep in mind, this is not a marshalling framework but rather a way to ease the json mapping with data objects.

**Comment by msavy** [comment]
> it seems reasonnable we could have a annotation config that controls this behavior and have all properties in the converter like @DataObject(generateAll=true)
That would be great!

> do you mean that something that is Serializable could be marshalled to byte[] ?
I could be completely wrong - but I just mean that something implementing Serializable would /also/ always be a valid @DataObject, right? You could use that to implicitly assign @DataObject status when such an object is encountered.

**Comment by vietj** [comment]
The problem is that handling Serializable would not allow to control the converted graph as many classes implements Serializable and create circularity problems. So it's a no.

**Comment by msavy** [comment]
Ah, understood - I hadn’t thought of cyclical graph issues. 

The annotation solution we’ve arrived earlier would be excellent for me!

Thanks again, @vietj
