### ISSUE TITLE
PropertyInfo.getGetterMethod returns some static methods

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-codegen#150]
Hi:

JdkSSLEngineOptions.isAlpnAvailable
OpenSSLEngineOptions.isAlpnAvailable
OpenSSLEngineOptions.isAvailable
These three getter methods are static method
and in PropertyInfo we couldn't separate non-static and static method
getGetterMethod only return a string with its name
so is it possible to add a wrapper of these 3 methods?
or add another getStaticGetterMethod to PropertyInfo?

For Clojure, auto generated method need to know whether it is static or non-static
There are several ways to walk around with these issue
for now we manually change the generated api
or using reflection maybe to check whether the method is static
or adding exceptional codes into our templ...
but the most elegant way is to add 1 separate method to PropertyInfo

Hope it helps

**Comment by vietj** [comment]
thanks for  reporting
