### ISSUE TITLE
Concern about package-info.java

### ISSUE THREAD

**Issue by LamaBimal** [vert-x3/vertx-codegen#155]
I am not able to understand the use of package-info.java with @ModuleGen. Is it necessary for the the vertx proxy-service. I didn't find the information of package-info in the documentation. URL: http://vertx.io/docs/vertx-service-proxy/java/
Can we ignore package-info.java file with the implementation of vertx-codegen.

**Comment by vietj** [comment]
it's actually necessary so the code generator knows more things about the jar
