### ISSUE TITLE
Vertx code generation failed - Illegal type java.lang.String[] of kind ARRAY

### ISSUE THREAD

**Issue by deodeveloper** [vert-x3/vertx-codegen#166]
Vertx code generation failed - Illegal type java.lang.String[] of kind ARRAY
It failed for Entities having annotation of DataObject, but the entity has a field that returns a string array.

For details, please see
[https://stackoverflow.com/questions/49188428/vertx-code-generation-failed-illegal-type-java-lang-string-of-kind-array](https://stackoverflow.com/questions/49188428/vertx-code-generation-failed-illegal-type-java-lang-string-of-kind-array)

**Comment by vietj** [comment]
Vert.x does not support arrays, so you need to use a `List<String>` for the getters and setters, the internal value remain an array.
