### ISSUE TITLE
Support handler params for Future will nullable type

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-codegen#180]
`<T> void executeBlocking(Handler<Future<@Nullable T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<@Nullable T>> resultHandler);`

fails the build with:

```
[ERROR] diagnostic: /home/tsegismont/Projets/eclipse/vert.x/src/main/java/io/vertx/core/WorkerExecutor.java:51: error: Could not generate model for io.vertx.core.WorkerExecutor#<T>executeBlocking(io.vertx.core.Handler<io.vertx.core.Future<T>>,boolean,io.vertx.core.Handler<io.vertx.core.AsyncResult<T>>): type io.vertx.core.Handler<io.vertx.core.Future<T>> is not legal for use for a parameter in code generation
  <T> void executeBlocking(Handler<Future<@Nullable T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<@Nullable T>> resultHandler);
           ^
```

It works fine with:

`<T> void executeBlocking(Handler<Future<T>> blockingCodeHandler, boolean ordered, Handler<AsyncResult<@Nullable T>> resultHandler);`

**Comment by tsegismont** [comment]
Blocks eclipse/vert.x#2453

**Comment by tsegismont** [comment]
@vietj can you point me to the test I should modify? It seems `NullableTCK ` is not used anymore.

**Comment by vietj** [comment]
TCK files are only used by languages such as Ceylon etc...

**Comment by vietj** [comment]
look at `ClassNullableTest`

**Comment by tsegismont** [comment]
> TCK files are only used by languages such as Ceylon etc...

Ha, I remember now. The alt lang implementation use it to make sure they can make a call to all these methods and get the correct result.

> look at ClassNullableTest

Thanks!

**Comment by tsegismont** [comment]
@vietj I made some progress on this. I pushed tests to a branch, see 08e846ed12904ab6282246f3d5b4e80e24972605

I had to annotate `Future` with `@VertxGen`, as in Vert.x core. Otherwise, the generation process fails early (arbitrary objects cannot be used as `Handler` params).

Now in the new test I can reproduce the issue (test passes with `Handler<Future<T>>` but fails with `Handler<Future<@Nullable T>>`.

Looking at the code, this is expected, as we have test like:

```java

  @Test
  public void testMethodWithInvalidNullableTypeArgumentHandler() throws Exception {
    assertGenInvalid(MethodWithInvalidNullableTypeArgumentHandler.class);
  }

@VertxGen
public interface MethodWithInvalidNullableTypeArgumentHandler {

  <T> void method(Handler<Generic<@Nullable T>> obj);

```

I could simply remove:

```java
            if (paramType.isNullable()) {
              return false;
            }
```

from `io.vertx.codegen.ClassModel#isVertxGenInterface`. But this check is here for a reason I guess.

Can you explain why?

**Comment by vietj** [comment]
I think actually it's a legacy thing and now it could be legal again.

**Comment by vietj** [comment]
we need to check with changing TCK how it will work for other languages I guess

**Comment by tsegismont** [comment]
@vietj I came back to this yesterday and reworked the changes (please see d1c7ebc)

But as I was starting to try the TCK on an alternative language I was wondering how this could be useful. Let's take this method from the TCK as an example:

```java
void methodWithNullableStringHandlerApi(boolean notNull, Handler<GenericRefedInterface<@Nullable String>> handler);
```

When the code is generated in the alternative lang, we have no idea how to deal with the `@Nullable` param info. Because what we do is simply creating a handler function for a `GenericRefedInterface`.

So I think that this constraint on `Nullable` was present for a good reason, and we shouldn't change it.

Does that make sense?

**Comment by vietj** [comment]
I believe a language can handle it, the `GenericRefedInterface` generated proxy can have a boolean saying wether or not to accept null objects and when `methodWithNullableStringHandlerApi ` is called, the language instantiates this proxy with the nullable flag

**Comment by vietj** [comment]
although it may not worth to implement it, what is the original use case ?

**Comment by vietj** [comment]
the case is for `Future`

**Comment by tsegismont** [comment]
@vietj you asked me to file this issue and take a look before we merge eclipse/vert.x#2453

I'm not sure about how this boolean would work. If the parameter type can be nullable, then I think it should be denoted by the api class itself, not another class using it. Let's take an example. Why writing:

```java
interface Something {
  void method(Handler<GenericRefedInterface<@Nullable String>> handler);
}

@VertxGen
public interface GenericRefedInterface<T> {
  @Fluent
  GenericRefedInterface<T> setValue(T value);
  T getValue();
}
```

instead of:

```java
interface Something {
  void method(Handler<GenericRefedInterface<String>> handler);
}

@VertxGen
public interface GenericRefedInterface<T> {
  @Fluent
  GenericRefedInterface<T> setValue(@Nullable T value);
  @Nullable T getValue();
}
```

The latter makes more sense to me and I believe is already supported.

**Comment by tsegismont** [comment]
@vietj in reply to your other comment, yes I don't believe it's a good use of time before 3.6 to look further into this, considering we have no bug or issue reported.

**Comment by vietj** [comment]
@tsegismont yes there are two ways to handle this and both don't have the same semantic. the `Future` class cannot declare its value to be `@Nullable` because it's not nullable all the time, the nullable decision is based on the method that declares the `Future` type.

let's leave this aside for the moment, with 4.0 we will use `CompletionStage` for return type and then `Future` would only be used differently.

**Comment by tsegismont** [comment]
Closing, may or not be relevant in 4.0
