### ISSUE TITLE
Code generated by Vert.x in Gradle based projects is not picked up in Eclipse with Buildship

### ISSUE THREAD

**Issue by vorburger** [vert-x3/vertx-codegen#182]
@pmlopes when I get an answer to https://discuss.gradle.org/t/how-to-add-srcdir-only-for-eclipse-buildship/27007, then I think it would be helpful to anyone else who wants to use the Vert.x Code Generator with Gradle to add documentation to the README.md in this project, and adjust the generator which produces the Gradle example which comes out of https://vertx-starter.jetdrone.xyz/#gradle (where are the sources for that?), with the respective appropriate configuration in build.gradle.

**Comment by vietj** [comment]
is this something you can contribute @vorburger ?

**Comment by pmlopes** [comment]
The generation template is here: https://github.com/pmlopes/vertx-starter/blob/master/templates/gradle/build.gradle but it looks that the Metadata must be updated as all dependencies are listed as compile scope

**Comment by vorburger** [comment]
==> https://github.com/pmlopes/vertx-starter/issues/17
--> https://github.com/pmlopes/vertx-starter/pull/16/files

> is this something you can contribute @vorburger ?

@vietj done

> it looks that the Metadata must be updated as all dependencies are listed as compile scope

for `compileOnly` ? That wasn't even the problem I meant here - have left as a _TODO_, for later.
