### ISSUE TITLE
allow Map<String, Object> type as parameter type

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-codegen#199]
Maps are allowed as parameters as long as the key type is String and the value type is known.

There are cases when it would be useful to allow Object for the cases where json would be too restrictive.  For example template engines.

**Comment by eutkin** [comment]
DataObject should be able to convert to json. If you have a Map <String, Object> that conveys to json, maybe you should use JsonObject?

**Comment by pmlopes** [comment]
@eutkin, the point here is when json types are too restrictive, for example template engines could receive a non json like say a pojo that can be used by the template to perform an action, or some more exotic type like a xml structure for example...

**Comment by eutkin** [comment]
restrictive because they must be transmitted via the event bus

**Comment by pmlopes** [comment]
@eutkin not necessarily, not all types are expected to be event bus friendly, look for example at data objects, they can't be used in the eventbus without a codec or encoding to json. The case I'm describing here is valid, a template engine can use any object type and json is not enough.
