### ISSUE TITLE
Force Vertx Rx CodeGen To Generate MayBe As Return Type(Kotlin)

### ISSUE THREAD

**Issue by c-nnooka** [vert-x3/vertx-codegen#200]
I am using following Kotlin code to generate proxy (This will also generate Rx methods)

```
@ProxyGen
@VertxGen
interface JobService {
    @Fluent
    fun getCertain(jobId: Int, handler: Handler<AsyncResult<Job?>>): JobService
}

When I see generated Rx Code it is as follows.

public Single<Job> rxGetCertain(int jobId) { 
   return new io.vertx.reactivex.core.impl.AsyncResultSingle<Job>(handler -> {
     getCertain(jobId, handler);
   });
}
```

Issue:-

Unfortunately i am not able to use this in Kotlin as kotlin won't allow null values for non-null fields and it is throwing following exception.

`java.lang.IllegalArgumentException: Parameter specified as non-null is null`

How do i force Vertx CodeGen to generate return type as MayBe so that my code works without any issues in kotlin.

**Comment by vietj** [comment]
you need to write:

```
@ProxyGen
@VertxGen
interface JobService {
    @Fluent
    fun getCertain(jobId: Int, handler: Handler<AsyncResult<@Nullable Job?>>): JobService
}
```

where `@Nullable` is codegen annotation.

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by c-nnooka** [comment]
can it be reopened ?

**Comment by vietj** [comment]
can you open this issue in the vertx-lang-kotlin instead ?
