### ISSUE TITLE
Support Interface with No Methods When it Extends A Base Interface with Methods

### ISSUE THREAD

**Issue by sherl0cks** [vert-x3/vertx-codegen#204]
See https://github.com/vert-x3/vertx-service-proxy/issues/74

This reproducer is created by following @vietj 's advice to remote @VertxGen from the base interface. Just load the maven module and you should get an IDE compiler error (`Interface io.openinnovationlabs.cabit.domain.dispatch.DriverRepository does not contain any methods for generation
`). Else `mvn clean compile` will do as well: https://github.com/sherl0cks/explore-ddd-2018-demo/tree/vertx-codegen-204/cabit/dispatcher. Adding back in the @VertxGen annotation results in `Type variable bounds not supported io.openinnovationlabs.cabit.domain.Aggregate`

**Comment by vietj** [comment]
I think I removed this limitation recently

**Comment by vietj** [comment]
this commit removed this limitation https://github.com/vert-x3/vertx-codegen/commit/ea1b1a885150b1e93f5f4fbc95a4e6ec369efd25#diff-7c8b812b9ac2f99d87c64bed561bc9aa

**Comment by vietj** [comment]
can you check with master ?
