### ISSUE TITLE
Attempt to recreate a file for type

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/vertx-codegen#221]
I'm trying a project setup with `vertx-codegen` for `@DataObject`, `vertx-service-proxy` for `@ProxyGen` and `vertx-web-api-service` for `@WebApiServiceGen` and during compiling I get the following error:

```java
Could not generate element for io.slinkydeveloper.debtsmanager.models.AuthCredentials: Attempt to recreate a file for type io.slinkydeveloper.debtsmanager.models.AuthCredentialsConverter
```

I import all three deps as `processor`

Tested with openjdk 8/9/11

**Comment by slinkydeveloper** [comment]
Ok so after more investigation I have a clear view on it. When you load two or three annotation processors, the jvm compare processors each other. `WebApiServiceGenProcessor` overrides `Set<String> getSupportedAnnotationTypes()` and jvm triggers code generation in both classes.

**Comment by slinkydeveloper** [comment]
Opened a topic on mailing list https://groups.google.com/forum/#!topic/vertx-dev/E_M7wagLbnw

**Comment by vietj** [comment]
I think that was resolved with the usage of a single generator
