### ISSUE TITLE
TestDataObject - equals() method "behaviour" + hashCode()

### ISSUE THREAD

**Issue by aaloise** [vert-x3/vertx-codegen#222]
When trying to upgrade vertx-lang-groovy to 2.5.x, some tests show java.lang.AssertionError: null because of the equals() method of TestDataObject.

Currently the method is like this:

```
  @Override
  public boolean equals(Object obj) {
    if (obj instanceof TestDataObject) {
      TestDataObject that = (TestDataObject) obj;
      return Objects.equals(foo, that.foo) && bar == that.bar && wibble == that.wibble;
    }
    return false;
  }
```

The Assertion passes if the method is changed to something like this:

```
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    TestDataObject that = (TestDataObject) o;
    return getBar() == that.getBar() &&
      Double.compare(that.getWibble(), getWibble()) == 0 &&
      Objects.equals(getFoo(), that.getFoo());
  }
```

Also, implementing hashCode() to TestDataObject would be interesting because of the use of Sets in tests.

**Comment by vietj** [comment]
why is it passing with this method instead of the actual one ?

**Comment by aaloise** [comment]
Digging a little more, I realized that equals() wasn't the problem, but the absence of hashCode() method. CollectionTCKImpl uses LinkedHashSet, and without hashCode(), contains(Object o) returns false even if objects are equals due to internal behaviour of (Linked)HashSet.

Basically is because of Java equals() and hashCode() Contract.

**Comment by aaloise** [comment]
Just tested with:

```
  @Override
  public boolean equals(Object obj) {
    if (obj instanceof TestDataObject) {
      TestDataObject that = (TestDataObject) obj;
      return Objects.equals(foo, that.foo) && bar == that.bar && wibble == that.wibble;
    }
    return false;
  }
```
and:

```
  @Override
  public int hashCode() {
    return Objects.hash(getFoo(), getBar(), getWibble());
  }
```

And it worked. So equals() doesn't necessarily needs to be updated. Current code and the one I suggested are fine. But hashCode() is needed.

**Comment by vietj** [comment]
can you make a PR for hashcode ?

**Comment by aaloise** [comment]
PR submitted

https://github.com/vert-x3/vertx-codegen/pull/223
