### ISSUE TITLE
Dagger2 annotation compilation conflict ?

### ISSUE THREAD

**Issue by lemon-li** [vert-x3/vertx-codegen#231]
Hello, I have a issue. 
When I add the codegen plugin, there is a problem with the compilation. I don't know how to modify my pom.xml.
my project already has a dagger2 plugin.
**pom.xml:** 

> <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-codegen</artifactId>
      <version>${vertx.version}</version>
      <classifier>processor</classifier>
 </dependency>

> <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-service-proxy</artifactId>
      <version>${vertx.version}</version>
</dependency>

> <plugins>
    <plugin>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>${maven-compiler-plugin.version}</version>
      <configuration>
        <source>${java.version}</source>
        <target>${java.version}</target>
        <compilerArgument>-Xlint:unchecked</compilerArgument>
        <annotationProcessors>
          <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
        </annotationProcessors>
        <annotationProcessorPaths>
          <path>
            <groupId>com.google.dagger</groupId>
            <artifactId>dagger-compiler</artifactId>
            <version>${dagger.version}</version>
          </path>
        </annotationProcessorPaths>
      </configuration>
    </plugin>
</plugins>

I get an error: **Annotation processor 'io.vertx.codegen.CodeGenProcessor' not found**
But if I remove dagger2, vertx codegen can generate code.

Thanks in advance.

**Comment by vietj** [comment]
do you have two < annotationProcessor> tags ?

**Comment by lemon-li** [comment]
@vietj only one , I don't know how to configure it, compatible with dagger2..

**Comment by lemon-li** [comment]
I solved this way...
> <executions>
            <execution>
              <id>default-compile</id>
              <goals>
                <goal>compile</goal>
              </goals>
              <configuration>
                <annotationProcessorPaths>
                  <path>
                    <groupId>com.google.dagger</groupId>
                    <artifactId>dagger-compiler</artifactId>
                    <version>${dagger.version}</version>
                  </path>
                </annotationProcessorPaths>
              </configuration>
            </execution>
            <execution>
              <id>vertx-compile</id>
              <goals>
                <goal>compile</goal>
              </goals>
              <configuration>
                <annotationProcessors>
                  <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
                </annotationProcessors>
              </configuration>
            </execution>
          </executions>
### WARNING: Processed element com.seasungames.xxxx.impl.xxxImpl is in an implementation package
Why is there this warning?

**Comment by vietj** [comment]
it's a warn of the processor because the code is in an .impl. package I guess we could remove this check in the processor as now it is more widely used beyond vertx stack usage

**Comment by lemon-li** [comment]
Thanks, Because I started compiling, many such warnings and info..
I modify my pom.xml
test: compile success , dagger2 file and proxy generate success..

> <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <compilerArgument>-Xlint:unchecked</compilerArgument>
            <annotationProcessorPaths>
              <path>
                <groupId>com.google.dagger</groupId>
                <artifactId>dagger-compiler</artifactId>
                <version>${dagger.version}</version>
              </path>
              <path>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-codegen</artifactId>
                <version>${vertx.version}</version>
                <classifier>processor</classifier>
              </path>
              <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-service-proxy</artifactId>
                <version>${vertx.version}</version>
              </dependency>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
But I don't know if this is correct?

**Comment by lemon-li** [comment]
solved
