### ISSUE TITLE
Generated converter not support BigDecimal.

### ISSUE THREAD

**Issue by Breggor** [vert-x3/vertx-codegen#237]

**Comment by Breggor** [comment]
POJO field type BigDecimal cannot generate converter

**Comment by vietj** [comment]
That's currently expected.

**Comment by pendula95** [comment]
Any progress on this?

**Comment by slinkydeveloper** [comment]
Hi, in Vert.x you can extend the code generation of Data object converters with new `JsonCodec` feature.

**Comment by pendula95** [comment]
@slinkydeveloper Can you reference some documentation or example?

**Comment by slinkydeveloper** [comment]
We have still nothing deployed, but you can find some documentation in readme https://github.com/vert-x3/vertx-codegen#data-objects
