### ISSUE TITLE
@RxGen classes not getting generated

### ISSUE THREAD

**Issue by lalithakulkarni** [vert-x3/vertx-codegen#245]
Trying out the [Vertx-Wiki](https://github.com/stakah/vertx-wiki/tree/aedf7933a71fa7ca96e33fe88c8d42649a48f3a9). When I upgrade the vertx version anything beyond 3.6.0, the RX version of the service does not get generated. Is this the intended behavior?

**Comment by vietj** [comment]
have you tried the latest version of vertx-wiki ?

**Comment by vietj** [comment]
can you try the 3.6 branch https://github.com/vert-x3/vertx-guide-for-java-devs/blob/3.6 ?
