### ISSUE TITLE
Annotation processor 'io.vertx.codegen.CodeGenProcessor' not found with gradle

### ISSUE THREAD

**Issue by superkoh** [vert-x3/vertx-codegen#247]
My build.gradle:

  plugins {
    id 'org.springframework.boot' version '2.1.3.RELEASE'
    id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.newsbreakapp'
version = 'release'
sourceCompatibility = '11'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    vertxVersion = '3.6.3'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
//    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation "io.vertx:vertx-core:$vertxVersion"
    implementation "io.vertx:vertx-web:$vertxVersion"
    implementation "io.vertx:vertx-web-client:$vertxVersion"
    implementation "io.vertx:vertx-rx-java2:$vertxVersion"
    implementation "io.vertx:vertx-jdbc-client:$vertxVersion"
    implementation "io.vertx:vertx-codegen:3.6.3"
    implementation "io.vertx:vertx-service-proxy:3.6.3"
    implementation group: 'org.reflections', name: 'reflections', version: '0.9.11'
    implementation "com.zaxxer:HikariCP:3.3.1"
    runtimeOnly('mysql:mysql-connector-java')
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

task annotationProcessing(type: JavaCompile, group: 'build') { // codegen
    source = sourceSets.main.java
    classpath = configurations.compile + configurations.compileOnly
    destinationDir = project.file('src/main/generated')
    options.compilerArgs = [
            "-proc:only",
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${project.projectDir}/src/main"
    ]
}

compileJava {
    targetCompatibility = 11
    sourceCompatibility = 11

    dependsOn annotationProcessing
}

sourceSets {
    main {
        java {
            srcDirs += 'src/main/generated'
        }
    }
}

**Comment by stephen-huang** [comment]
you can try put processor in classpath:
annotationProcessor "io.vertx:vertx-codegen:$vertxVersion:processor"

**Comment by chefhoobajoob** [comment]
@stephen-huang: the new `annotationProcessor` configuration does not help. I have this same problem using that configuration and this compiler task config:

```
def vertxVersion = "3.6.3"
dependencies {
    // ...some dependencies
    annotationProcessor "io.vertx:vertx-codegen:$vertxVersion"
   // ...more dependencies
}

task generatePolyglotApis(type: JavaCompile) {
    group 'build'
    description 'Generates Vertx js and rxjava shims'
    source = sourceSets.main.java
    classpath = configurations.annotationProcessor
    options.debugOptions.debugLevel = "source,lines,vars"
    options.compilerArgs = [
            "-proc:only",
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${projectDir}/src/main"
    ]
    destinationDir = file("${buildDir}/generated-sources/vertx")
}
```

**Comment by chefhoobajoob** [comment]
@superkoh: try the following:

Change the dependency configuration for the `vertx-codegen` lib from `implementation` to `annotationProcessor`:
```
   annotationProcessor "io.vertx:vertx-codegen:3.6.3"
```
Then, add the following line to the compiler task to run the processor:
```
    options.annotationProcessorPath = configurations.annotationProcessor
```

I still have other things to sort out, but this change got me past the `Annotation processor not found` problem.

**Comment by chefhoobajoob** [comment]
I think I've found the right configuration now. In my dependencies block, I have:

```
def vertxVersion = "3.6.3"
dependencies {
    // ...other dependencies
    compile "io.vertx:vertx-rx-java2:$vertxVersion"
    annotationProcessor "io.vertx:vertx-rx-java2-gen:$vertxVersion"
    annotationProcessor "io.vertx:vertx-codegen:$vertxVersion"
    // ...other dependencies
}
```
...in the codegen task I have:
```
task generatePolyglotApis(type: JavaCompile) {
    group 'build'
    description 'Generates Vertx js and rxjava shims'
    source = sourceSets.main.java
    options.annotationProcessorPath = configurations.annotationProcessor
    classpath = configurations.compile + configurations.compileOnly
    options.debugOptions.debugLevel = "source,lines,vars"
    options.compilerArgs = [
            "-proc:only",
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${projectDir}/src/main"
    ]
    destinationDir file("${buildDir}/generated-sources/vertx")
}
```

...and for the `javaCompile` task I have:
```
compileJava{
    dependsOn(generatePolyglotApis)
    options.debugOptions.debugLevel = "source,lines,vars"
    source    += sourceSets.vertxPolyglot.java
    options.compilerArgs += '-proc:none'
}
```

**Comment by slinkydeveloper** [comment]
Can we close it?

**Comment by bulivlad** [comment]
Still not working for me. It is also messing with lombok processor.

```
------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.14.4 x86_64
```

My dependencies and configuration tasks bit 

```
compile "io.vertx:vertx-service-proxy:$vertxVersion"
    compileOnly "io.vertx:vertx-codegen:$vertxVersion"
    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "io.vertx:vertx-codegen:$vertxVersion" 
```

```
sourceSets {
    vertxPolyglot {
        java {
            srcDirs += 'src/main/generated'
        }
    }
}

task generatePolyglotApis(type: JavaCompile) {
    group 'build'
    description 'Generates Vertx js and rxjava shims'
    source = sourceSets.main.java
    options.annotationProcessorPath = configurations.annotationProcessor
    classpath = configurations.compileClasspath + configurations.runtimeClasspath
    options.debugOptions.debugLevel = "source,lines,vars"
    options.compilerArgs = [
            "-proc:only",
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${projectDir}/src/main"
    ]
    destinationDir file("${buildDir}/generated-sources/vertx")
}

compileJava{
    dependsOn(generatePolyglotApis)
    options.debugOptions.debugLevel = "source,lines,vars"
    source    += sourceSets.vertxPolyglot.java
    options.compilerArgs += '-proc:none'
```

However it is working just fine when downgrading gradle to 4.x version with following dependencies
```
    compile "io.vertx:vertx-service-proxy:$vertxVersion"
    compile "io.vertx:vertx-codegen:$vertxVersion:processor"
```

**Comment by slinkydeveloper** [comment]
@bulivlad you must add vertx-service-proxy package too in annotationProcessor path

**Comment by bulivlad** [comment]
Thanks @slinkydeveloper. It did the trick. Also there is a gradle plugin here https://plugins.gradle.org/plugin/io.dotinc.vertx-codegen-plugin to do the config out of the box

**Comment by slinkydeveloper** [comment]
@bulivlad cool thank you! Add the plugin to [vertx-awesome](https://github.com/vert-x3/vertx-awesome#deployment) :smile:

**Comment by harrisonljones** [comment]
Thank you @slinkydeveloper . Took forever finding that one.

**Comment by rodrimmb** [comment]
Thank to @chefhoobajoob and @slinkydeveloper, with your help the code generation works for me. I share what I do:

`
dependencies {
    compile 'io.vertx:vertx-web:3.9.0'
    compile 'io.vertx:vertx-service-proxy:3.9.0'
    compile 'io.vertx:vertx-web-client:3.9.0'
    compile 'io.vertx:vertx-jdbc-client:3.9.0'
    compile 'io.vertx:vertx-web-templ-freemarker:3.9.0'
    compile 'com.github.rjeschke:txtmark:0.13'
    compile 'io.vertx:vertx-jdbc-client'
    compile 'org.postgresql:postgresql:42.2.12'
    compile 'ch.qos.logback:logback-classic:1.2.3'

    compileOnly 'io.vertx:vertx-codegen:3.9.0'

    testCompile 'io.vertx:vertx-junit5:3.9.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'

    annotationProcessor 'io.vertx:vertx-codegen:3.9.0'
    annotationProcessor 'io.vertx:vertx-service-proxy:3.9.0'
}

sourceSets {
    generated{
        java.srcDir "${projectDir}/src/generated/java"
    }
}

task generateProxies(type: JavaCompile) {
    group 'build'
    description 'Generates the Vert.x proxies'
    source = sourceSets.main.java
    classpath = configurations.compile + configurations.compileOnly + configurations.annotationProcessor
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs = [
            "-proc:only",
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${projectDir}/src/main"
    ]
    destinationDir = file("${projectDir}/src/generated/java")
}

compileJava{
    dependsOn generateProxies
    source += sourceSets.generated.java
    options.compilerArgs += '-proc:none'
}

clean {
    delete += sourceSets.generated.java.srcDirs
}
`

I hope this help.
