### ISSUE TITLE
BUG Not working with maven-compiler-plugin version 3.8.0

### ISSUE THREAD

**Issue by pendula95** [vert-x3/vertx-codegen#249]
When Using maven-compiler-plugin version 3.8.0 there is strange behaviour. If generated folder is not present everything works well. If you run mvn clean package generated folder is never updated and classes are newer generated. I haven't tested backward computability but everything works fine when using 3.1 that is present in documentation.

This has a side effect that I can not link  because when I ran the built fat jar Proxy Classes can not be found. They are present in jar but for some reason they thro exception ClassNotFound. I guess this is connected to the first case.

**Comment by slinkydeveloper** [comment]
Can you share a reproducer?

**Comment by pendula95** [comment]
Here is the reproduction:
[starter.zip](https://github.com/vert-x3/vertx-codegen/files/3094993/starter.zip)

mvn clean package
ls -l src/main/generated/com/bug/dropwizard/starter/
Note the timestamp of the file

Wait 1 min:
mvn clean package
ls -l src/main/generated/com/bug/dropwizard/starter/
Note the timestamp has not be changed, so this means classes are not regenerated.

This is probably the issue with the Proxy Classes not found on the class path, but reproduction is not included here.

**Comment by slinkydeveloper** [comment]
There is any particular reason to have the code generated in `src/main/generated`? Because you must configure the maven clean plugin and maven jar plugin to find the `src/main/generated` directory. Otherwise, just remove all codegen configuration and let the maven compiler plugin choose for you

**Comment by pendula95** [comment]
This is taken from example project. My question is why there is a different behaviour between version 3.1 and 3.8. What has changed so 3.1 works as expected with this configuration and with 3.8 this doesn't work?

**Comment by slinkydeveloper** [comment]
I honestly have no idea :) Probably the `src/main/generated` was added automatically to project sources (and cleanable sources), while now they are configured in other way and you must do it automatically, unless you leave the default ones. Anyway I close as this is an issue not related to vert but some maven wrong configuration problem.
