### ISSUE TITLE
Support for static fromJson-method in DataObject-classes

### ISSUE THREAD

**Issue by michaelom** [vert-x3/vertx-codegen#25]
> Data object classes must provide a constructor which takes a single io.vertx.core.json.JsonObject parameter.

It would be more convenient to enforce either a a constructor which takes a single io.vertx.core.json.JsonObject parameter or a public static factory method as in:
```
@DataObject
public class Customer {
      public static Customer fromJson(JsonObject jsonObject) {
      ...
      }
}
```

I think this approach is also more idiomatic than using a constructor. Having multiple (non-overloaded) constructors with different argument types does not feel right.

**Comment by vietj** [comment]
implemented.
