### ISSUE TITLE
Functions in parent interfaces with generics signatures support

### ISSUE THREAD

**Issue by CasterKKK** [vert-x3/vertx-codegen#254]
# Description
## A parent interface:
```java
@VertxGen
public interface AbstractService<S extends AbstractService> extends AutoCloseable {
  @Fluent
  S create(JsonObject entity, Handler<AsyncResult<String>> handler);
}
```

## A child interface:
```java

@VertxGen
public interface UserService
    extends AbstractService<UserService> {
  @Fluent
  UserService getByEmail(String email, Handler<AsyncResult<User>> handler);
}
```

## Get error when compiling:
```
SEVERE: Could not generate model for com.ra.wonderland.common.service.AbstractService: Type variable bounds not supported com.ra.wonderland.common.service.AbstractService
io.vertx.codegen.GenException: Type variable bounds not supported com.ra.wonderland.common.service.AbstractService
	at io.vertx.codegen.ClassModel.traverseType(ClassModel.java:622)
```

So I debug and find that VertxGen will find `S extends AbstractService` is `!isObjectBound`. But when I remove `@VertxGen` from the parent interface, I can only get child function in my generated class, like:

```java
@io.vertx.lang.rx.RxGen(com.ra.wonderland.user.service.UserService.class)
public class UserService {
 ...
  public com.ra.wonderland.user.reactivex.service.UserService getByEmail(String email, Handler<AsyncResult<User>> handler) { 
    delegate.getByEmail(email, handler);
    return this;
  }

  public Single<User> rxGetByEmail(String email) { 
    return io.vertx.reactivex.impl.AsyncResultSingle.toSingle(handler -> {
      getByEmail(email, handler);
    });
  }
...
}
```
Here I can only get `getByEmail` from `UserService`, but I cannot get `create` from `AbstractService`.

So for now I can only write something like:

```java
@VertxGen
public interface UserService
    extends AbstractService<UserService> {
  @Fluent
  UserService getByEmail(String email, Handler<AsyncResult<User>> handler);

@Override
@Fluent
  UserService create(JsonObject entity, Handler<AsyncResult<String>> handler);
}
```

Where I have to repeat all the functions from parent interfaces, which is really ugly.

# Question

Any suggestions? Or maybe it is only the `rx-java2-gen`'s problem?

**Comment by vietj** [comment]
suggestion is to avoid using self bound generics and instead use return type covariance in java, that's how it is done in vertx APIs

**Comment by CasterKKK** [comment]
--- Copy from updated question part ---

Thanks @vietj for the quick and concise answer, I know your point is not to use generics in Parent Interface, but how about this situation?

## Parent Interface
```java
interface AbstractService<T extends AbstractModel> {
  @Fluent
  AbstractService getAll(Handler<AsyncResult<List<T>>> handler);
}
```

**Comment by vietj** [comment]
I think that should work if your AbstractInterface is not annotated with @VertxGen

**Comment by CasterKKK** [comment]
@vietj Finally, I found the correct way likes this:
```java
@VertxGen(concrete=false)
interface AbstractService<T> {
  @Fluent
  AbstractService getAll(Handler<AsyncResult<List<T>>> handler);
}
```
Where I should add `@VertxGen` annotation and **not use extends in generic signature**! But why? Isn't it more convenient if support the co- and contra- varience?
