### ISSUE TITLE
@VertxGen/@ProxyGen: package for generated classes

### ISSUE THREAD

**Issue by michaelom** [vert-x3/vertx-codegen#26]
It is currently not possible to generate a service-proxy with vertx-rx on the classpath as the code generator will generate an rx-wrapper in the same package as the source file resulting in an error:

```
 error: duplicate class: xxx.MyService
```

Ported from https://groups.google.com/forum/#!topic/vertx/r3hpw-OvU0s:

> Julien Viet:
> hi,
>
>at the moment using codegen with non “io.vertx” package does not work well and there is definitely ?some serious work to do on this to make it possible.
>
>the main reason is that we hardcoded “io.vertx” package in some generating templates and we need to have a better way to do this.
>
>that’s definitely something we’re going to do
>
>if temporarily you can use io.vertx package it would a good work around.

**Comment by vietj** [comment]
this has been fixed and now it should work for non _io.vertx_ packages, please see https://github.com/vert-x3/vertx-codegen#modules for the details.

**Comment by michaelom** [comment]
Hi Julien,

works as advertised. 
If you are interested, I let you and Tim know how we use service-proxy-gen to built SOA-style services in a microservice architecture prototype.
