### ISSUE TITLE
Support collections of DataObject

### ISSUE THREAD

**Issue by michaelom** [vert-x3/vertx-codegen#28]
imported from https://groups.google.com/forum/#!searchin/vertx/dataobject/vertx/sFFO1KasSYU/Hn4ElRG69SoJ

This is a feature request for methods that take collections of DataObjects as arguments (or type parameters of arguments)
```
void do(Handler<AsyncResult<List<MyDataObject>> resultHandler);
```

**Comment by vietj** [comment]
we definitely should support this.

**Comment by xtermi2** [comment]
I need this feature too

**Comment by vietj** [comment]
So actually this was implemented since milestone 6

**Comment by michaelom** [comment]
great job!
