### ISSUE TITLE
custom generator loader not found

### ISSUE THREAD

**Issue by changchengqin** [vert-x3/vertx-codegen#292]
I have a custom generator loader in my source base and declared as a META-INF/services/io.vertx.codegen.GeneratorLoader JVM service.

But when I compile or build, it prompts an error:

Error:java: java.util.ServiceConfigurationError: io.vertx.codegen.GeneratorLoader: Provider com.xxx.xx.codegen.PublicServiceGenLoader not found.

**Comment by vietj** [comment]
make sure that your generator is on the same classpath than codegen so it can be loaded.

**Comment by changchengqin** [comment]
Thanks, it has been solved.
