### ISSUE TITLE
how does it work while use  @ParametersMapped with @DataObject

### ISSUE THREAD

**Issue by Ikki-Dai** [vert-x3/vertx-codegen#321]
### Questions

while use `@ParametersMapperd` to generate code, it gives my class `requires a JSON constructor`. but when use `@DataObject` it would generate a `**Converter.java` which contains a static method named `fromJson`.
so why does not combile them into my source as a JSON constructor?
and can fix the compile bug while use `@ParametersMapperd` separately.

### Version

4.0.0

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?
N/A

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* any idea can enhance my experience to use the codegen in IDE?

**Comment by vietj** [comment]
Actually you need to use the generated converter in your source code (in the json constructor).

The generator cannot modify your code.

e.g like here https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L173
