### ISSUE TITLE
Fields starting with `_` are ignored in both de/serialization

### ISSUE THREAD

**Issue by mohamnag** [vert-x3/vertx-codegen#326]
### Version

v4.0.3

### Context

I stumbled up on this problem while modeling MongoDB docs in Java and using codegen for de/serialization. It seems that fields (getters and setters for fields) starting with an `_` are ignored.

### Do you have a reproducer?

Consider following Java class:
```java
@DataObject(generateConverter = true, publicConverter = false)
public class SomeMongoDoc {
  private String _id;

  public String get_id() {
    return _id;
  }

  public void set_id(String _id) {
    this._id = _id;
  }

  // ... toJson and JsonObject constructor as usual

}
```

the generated converter completely ignores the `get_id()` and `set_id()`.

**Comment by vietj** [comment]
yes I think this is an invalid property name because of the _

**Comment by vietj** [comment]
you can I think map this field yourself using some code easily

**Comment by mohamnag** [comment]
a manual mapping is definitely possible, however this will defeat the purpose of codegen.

also regarding "invalid" name, this is yet another assumptions of vertx, which is allowed in Java as the base language. besides vertx's codegen I'm using lombok and mapstruct for code generation and both of them handle this case with no problem. so I don't see why vertx should make an extra exception here not to accept what language allows.
