### ISSUE TITLE
Code generation does not with with modules and JDK 16

### ISSUE THREAD

**Issue by jeremy-florte** [vert-x3/vertx-codegen#327]
### Version

4.0.3

### Context

It is an update of a previous issue that raised when using modules and code generator with a JDK 11.
Testing with JDK 16 raised another issue because now, instead of throwing NPE, java implementation returns `null`.

This stands in `CodeGen` class.

Previous update was (line 71):

```java

Predicate<Element> implFilter = elt -> {
  PackageElement pkg;
  try {
    pkg = elementUtils.getPackageOf(elt);
  } catch (NullPointerException e) {
  // This might happen with JDK 11 using modules and it looks like a JDK bug
  return true;
  }

  String fqn = pkg.getQualifiedName().toString();
  return !fqn.contains(".impl.") && !fqn.endsWith(".impl");
};

```

### Steps to reproduce
[service-proxy-howto.zip](https://github.com/vert-x3/vertx-codegen/files/6258501/service-proxy-howto.zip)

1. uncompress the provided archive
2. run command `mvn compile exec:java`
3. you should get an error about a null pointer exception: 

```bash
 Fatal error compiling: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.PackageElement.getQualifiedName()" because "pkg" is null
```

### Proposed fix

The issue stands in CodeGen class. Following fix resolves the issue (tested with latest 4.1.0-SNAPSHOT version):

```java
Predicate<Element> implFilter = elt -> {
  PackageElement pkg;
  try {
    pkg = elementUtils.getPackageOf(elt);
  } catch (NullPointerException e) {
  // This might happen with JDK 11 using modules and it looks like a JDK bug
  return true;
  }

  if (null == pkg) {
    return true;
  } else {
    String fqn = pkg.getQualifiedName().toString();
    return !fqn.contains(".impl.") && !fqn.endsWith(".impl");
  }
};
```

A kind of shorter syntax could be:

```java
Predicate<Element> implFilter = elt -> {
  try {
    // Since JDK 16, method elementUtils.getPackageOf(Element) can return null instead of throwing a NPE.
    return Optional.ofNullable(elementUtils.getPackageOf(elt))
                   .map(pkg -> pkg.getQualifiedName().toString())
                   .map(fqn -> !fqn.contains(".impl.") && !fqn.endsWith(".impl"))
                   .orElse(true);
  } catch (NullPointerException e) {
    // This might happen with JDK 11 using modules and it looks like a JDK bug
    return true;
  }
};
```

_NB: does not compile with a JDK 16 (compiles fine with JDK 11) but executes well with JDK 11 and 16._

### Extra

OS version: pop OS (kind of Ubuntu 20.04)
Java: 16 open JDK

**Comment by vietj** [comment]
@jeremy-florte can you provide a PR ?

**Comment by jeremy-florte** [comment]
Sure, I'm off today but I'll do it asap.

**Comment by jeremy-florte** [comment]
Could you give me write access to the repo ? My branch is ready but I cannot push.

**Comment by vietj** [comment]
you need to provide a pull request

**Comment by jeremy-florte** [comment]
P.R here: https://github.com/vert-x3/vertx-codegen/pull/328

**Comment by vietj** [comment]
thanks!
