### ISSUE TITLE
The class PathForCodeGenProcessor is not deleted and warns which fails the build with -werror

### ISSUE THREAD

**Issue by nickbreen-lmax** [vert-x3/vertx-codegen#336]
### Version

4.0.3

### Context

Builds with `-werror` fail.

https://github.com/vert-x3/vertx-codegen/blob/f7fd905e8ae083164b2da1cebac5c5afa8f7843d/src/main/java/io/vertx/codegen/CodeGenProcessor.java#L152-L162

This code creates an empty class file used to find the generation path.

The problem is when `-werror` is specified. This file produces a warning:

> warning: Unclosed files for the types '[PathForCodeGenProcessor]'; these types will not undergo annotation processing

### Do you have a reproducer?

The examples listed in the read me with `-werror` added as a javac option.

**Comment by nickbreen-lmax** [comment]
I believe that since this file is never _written_ to it does not get closed (and apparently also is not created on the filesystem) and "hangs around".

**Comment by nickbreen** [comment]
> where is `-werror` specified ? I'd like to reproduce this issue

Specified in javac's options in our builds.
