### ISSUE TITLE
Annotation processor isn't discovered by default

### ISSUE THREAD

**Issue by pabad** [vert-x3/vertx-codegen#35]
The module doesn't declare the processor as a service in META-INF, and as such the annotation processor is not recognized by default by javac.

I'm working on a project where there are three other annotations processors involved, and it took some time realizing that this one required adding the processor class explicitely when compiling. It also forced me to add all the other processors explicitely.

Is there a reason for this behavior?  If not please consider adding the service description. I can gladly send a pull request...

**Comment by vietj** [comment]
yes it's off because we don't necessarily run it via javac but via the `org.bsc.maven:maven-processor-plugin` plugin, by default it would be executed several times so we prefer to have this explicit configuration at the moment.
