### ISSUE TITLE
Generate toJson/fromJson on @DataObject if not explicitly provided

### ISSUE THREAD

**Issue by msavy** [vert-x3/vertx-codegen#37]
In cases where `@DataObject` is a simple POJO, it would be great to have this generated. Either that, or an efficient mechanism to go from POJO to JsonObject (which is the required return type on toJson).

In know in the past someone made this project to achieve the POJO -> JsonObject mapping https://github.com/Crunc/jackson-datatype-vertx . It's far better than maintaining manually, or doing something klutzy like encoding to JSON with Jackson, passing it into the JsonObject String constructor, which simply uses Jackson to decode it again!

**Comment by msavy** [comment]
I think this ties into https://github.com/vert-x3/vertx-codegen/issues/25 somewhat, as it'd be logical to have a factory method where the POJO is deserialized and used directly; rather than a JsonObject constructor, which forces you to use copy semantics.

**Comment by vietj** [comment]
duplicate with https://github.com/vert-x3/vertx-codegen/issues/15

**Comment by msavy** [comment]
@vietj #15  was only for Options classes though; that's not `@DataObject` right?

**Comment by vietj** [comment]
ah, actually options classes are previous @DataObject

**Comment by vietj** [comment]
I changed #15 to @DataObject

**Comment by msavy** [comment]
@vietj Aha, thanks! I thought it was some other type of options.
