### ISSUE TITLE
Allow byte array for languages supporting it

### ISSUE THREAD

**Issue by LarsTimm** [vert-x3/vertx-codegen#40]
Today all methods using Byte as type has to be marked with GenIgnore because some languages does not support it.

One example is this constructor for a Buffer:
    /**
     \* Create a new buffer from a byte[]. The byte[] will be copied to form the buffer.
     *
     \* @param bytes  the byte array
     \* @return  the buffer
     */
    @GenIgnore
    static Buffer buffer(byte[] bytes) {
      return factory.buffer(bytes);
    }

While some languages does not support a Byte type some do (Scala for instance), and it seems like a pity that all has to live with out these useful methods.

I propose a solution where we don't mark methods with Bytes in them as GenIgnore and instead let the individual languages decide if they can use it or not.

**Comment by vietj** [comment]
so you mean byte[] and not the byte primitive type, right ?

**Comment by LarsTimm** [comment]
Yes. Sorry for not being clear. 

I actually forgot at the byte type is supported, it's the byte[] that's not, or is it all "arrays"?

**Comment by vietj** [comment]
usually we model byte[] by Buffer. what would buy to use byte[] instead of Buffer ?

**Comment by LarsTimm** [comment]
Yes, but wouldn't it be useful to be able to construct a Buffer using byte[] and get it using getBytes().

Otherwise we are left with just getByte and setByte, which is cool but the individual languages might have more "advanced" operations for an array.

**Comment by vietj** [comment]
byte primitive type can be mapped today with a best effort according to the target language.

**Comment by LarsTimm** [comment]
Yes but that's not the case for byte[] because those methods are marked with GenIgnore. 

Specifically these methods from the Buffer would be great to have available in languages that can support it:

```java
/**
   * Create a new buffer from a byte[]. The byte[] will be copied to form the buffer.
   *
   * @param bytes  the byte array
   * @return  the buffer
   */
  @GenIgnore
  static Buffer buffer(byte[] bytes) {
    return factory.buffer(bytes);
  }

 /**
   * Returns a copy of the entire Buffer as a {@code byte[]}
   */
  @GenIgnore
  byte[] getBytes();

  /**
   * Returns a copy of a sub-sequence the Buffer as a {@code byte[]} starting at position {@code start}
   * and ending at position {@code end - 1}
   */
  @GenIgnore
  byte[] getBytes(int start, int end);
```

**Comment by EmadAlblueshi** [comment]
I hope to see that soon :+1:

**Comment by EmadAlblueshi** [comment]
@vietj Why there is an Rx-ified Buffer data type ? I think it should not be because it is like other vert.x data types JsonArray, JsonObject ... etc. What do you think ?

**Comment by vietj** [comment]
@EmadAlblueshi it's a generic converter, so it converts the types like others @VertxGen . It is different from others in the fact that they provide a unified API for dealing with buffers that works the same in all languages. So there is an rxified buffer because the rxjava was done with code generation. One could come up with an alternative handwritten rxjava implementation that would reuse the original buffer.

**Comment by EmadAlblueshi** [comment]
@vietj is it possible to exclude it from the generic converter like what you did with other data types ?

**Comment by EmadAlblueshi** [comment]
@vietj Honestly, I don't see any good reason to have two versions of Buffer data type in vertx-rx-java.

**Comment by vietj** [comment]
there is no good reason per se, the only justification is that it is something generally handled by the code generator.

maybe we can improve that somehow and hint rxjava to not create wrappers for it.

**Comment by vietj** [comment]
@EmadAlblueshi it could be specifically handled but then we would have not support for other languages supported by vertx

**Comment by EmadAlblueshi** [comment]
@vietj to hint rxjava to not create wrappers for it. That exactly what I meant which means only for **vertx-rx-java** and I believe this would make development much easier and handy.

so is other any further requirements needed to make this happen ?

**Comment by vietj** [comment]
@EmadAlblueshi retro-compatibility :-)

**Comment by vietj** [comment]
@EmadAlblueshi I fully agree with you that the rxjava code generation has room for improvements. Maybe you can make some research/prototype to see how it can be improved ?

**Comment by EmadAlblueshi** [comment]
@vietj I'm going to do my best :+1:
