### ISSUE TITLE
imports are not being properly generated anymore

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-codegen#43]
Example see LoggerHandler.java in vertx-web, in the end of the interface there is a enum "Format" that is used in the interface.

Now on the generated rx and groovy the import statements do not include that enum anymore and breaks compilation. It was working before.

**Comment by vietj** [comment]
comes from this commit : https://github.com/vert-x3/vertx-codegen/commit/a35f418bc1bf6b3272f9a4e3eb03bbf630b252ca - will add a test for this case in codegen and then fix it.
