### ISSUE TITLE
Map members missed in toJson/fromJson generateConverter

### ISSUE THREAD

**Issue by msavy** [vert-x3/vertx-codegen#48]
I have been using the new `generateConverter` and `inheritConverter` stuff. I've just noticed that the codegen skips simple types like Map in the generated `toJson`/`fromJson`, with results in an empty Map on deserialization.

i.e.

```
  public static void fromJson(JsonObject json, VertxServiceResponse obj) {
    if (json.getValue("code") instanceof Number) {
      obj.setCode(((Number)json.getValue("code")).intValue());
    }
    if (json.getValue("message") instanceof String) {
      obj.setMessage((String)json.getValue("message"));
    }
    // Should also be a header map entry, but it's missing!
  }
```

To test things out, I hacked the following into toJson/fromJson, and it works very nicely:

```
  public static void fromJson(JsonObject json, VertxServiceResponse obj) {
  
   // Hacked in by hand
    for (Entry<String, Object> entry : json.getJsonObject("headers").getMap().entrySet()) {
        if (entry.getValue() instanceof String) {
            obj.getHeaders().put(entry.getKey(), (String) entry.getValue());
        }
    }
  }

  public static void toJson(VertxServiceResponse obj, JsonObject json) {
   // Hacked in by hand
    if (obj.getHeaders() != null) {
        json.put("headers", obj.getHeaders());
    }
  }
```

So, hopefully it's not a drastic change. I was considering doing a PR, but I'm not sure what I should do in cases where the generic parameters aren't simple (especially when you don't control the source of those types, and hence can't annotate them).  I have much to learn in the magical realms of Java codegen!

Thanks again, gents.

**Comment by vietj** [comment]
so actually it will take some time to do because we haven't code generation established for various langs but that seems doable.

**Comment by vietj** [comment]
so actually this would work (no need to do anything in other langs) but the data in the Map<String, Object> needs to be like JsonObject, so that would kind of be an alias for JsonObject.

**Comment by vietj** [comment]
there is a PR for this

**Comment by msavy** [comment]
Fantastic, I'll test this out :-)

**Comment by vietj** [comment]
that's a good idea.
