### ISSUE TITLE
Is is possible to specify varargs/optional args?

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-codegen#5]
@see https://groups.google.com/d/topic/vertx/RWU7v1t4RFs/discussion

Many languages like groovy, python, js, etc... support this out of the box, in java we need to write a lot of overloading methods... what are the best practices to address this?

**Comment by vietj** [comment]
If I understand correctly, you are looking for varargs in @DataObject setters ?

**Comment by pmlopes** [comment]
Yes that was the idea

**Comment by vietj** [comment]
I think that it would complexify a bit the code generation, what does prevent you from using both ovelroaded varrags and List and have the varrars delegate to the List version ?

**Comment by vietj** [comment]
Complexify means that a non JVM language will need to have interop work right with this and also create the correct array type.

**Comment by vietj** [comment]
I'm closing this issue, if needed, overloading can provide both the list version and the varrags.
