### ISSUE TITLE
Suggested improvement WRT the types passed in the event bus

### ISSUE THREAD

**Issue by plenderyou** [vert-x3/vertx-codegen#57]
We have a existing datastructures from other products to use in the Proxy API's, it's not practical to re-write all these into DataObjects. I know I can convert them to JsonObjects but I think it would be useful to be able to register Codecs on the API methods:

e.g.
@Codec( name=SomeObject.class, codec=SomeObjectCodec.class)

I'm not sure if we can use the Codecs like you can Register on the event bus, but I think that would be nice, otherwise we could write a Serialiser for the object to and from Json.

**Comment by vietj** [comment]
hi, can you explain a bit more and give an example use case to give more concrete context ?

**Comment by plenderyou** [comment]
Sure I'll try.

At the moment the Proxy generation of services will only let you define a restricted set of datatypes for the parameters of the service, I'd like to be able to pass any type.

The underlying event bus supports this using message codecs  which serialise and deserialise the objects to a buffer. http://vertx.io/docs/apidocs/io/vertx/core/eventbus/MessageCodec.html

I'd like the same functionality to be available in the generation of the proxy, but to do this the proxy would have to know which codecs to use; I was suggesting being able to specify the codec to use for the parameter in the proxy definition.

so a method declaration would/could be

    void authenticate(@Codec( AuthInfoCodec.class ) final AuthInfo authInfo, @Codec( PlayerCodec.class) final Handler<AsyncResult<Player>> playerHandler);
 
Or perhaps at the method/class level

@Codec( AuthInfo.class , codec=AuthInfoCodec.class )
@Codec( Player.class , codec=PlayerCodec.class )
 void authenticate( final AuthInfo authInfo, @Codec( PlayerCodec.class) final Handler<AsyncResult<Player>> playerHandler);

The above would work for Java->Java services but I'm not sure if the implementation was in javascript what would happen ( I think that the javascript code can handle this).

We could define a new Serialisation type that always converts it to/from JsonObject as an alternative BUT why not go the next step and default it to Json.encode/decode

I hope this in now clear
