### ISSUE TITLE
How to use this standalone

### ISSUE THREAD

**Issue by mozinrat** [vert-x3/vertx-codegen#59]
I am not able to figure out how to use this codegen? I kind of get the idea that we have create a Json template to use, but how to actually use it. Is it possible to create a jar, then pass the Json template as parameter or do I have to create a build.gradle with the mentioned gradle script and do a gradle init.
I would really appreciate if you can help me with this. 

Is there a possibility to release something like spring-cli?

**Comment by vietj** [comment]
you need a build an annotation processing to make it work.

I will provide soon a maven build that creates a vanilla code generation people can use as a starter.

what would the cli be useful for too?

**Comment by vietj** [comment]
so actually I'm working a standalone CLI tool that should get you started.

**Comment by vietj** [comment]
should be done soon.

**Comment by vietj** [comment]
Hi, would you mind to check this project ? https://github.com/vietj/vertx-codegen-cli it provides a CLI that should help you generating files.

**Comment by mozinrat** [comment]
That looks really good, can you publish a short tutorial on how to write codgen.json for java/gradle system. I would majorly need vertx-web and vertx-rx. Really appreciate your help.
