### ISSUE TITLE
Generate getter - @fluent

### ISSUE THREAD

**Issue by mavencode01** [vert-x3/vertx-codegen#66]
I'm trying to expose a getter method in my service interface but keep getting this error

    io.vertx.codegen.GenException: Methods marked with @Fluent must have a return type that extends the type

Looks like there is little documentation out there....how can I resolve this ?

**Comment by cescoffier** [comment]
`@Fluent` annotated method must return an object of the current class. Have a look to: https://github.com/vert-x3/vertx-service-proxy/blob/master/src/main/asciidoc/index.adoc#return-types

**Comment by mavencode01** [comment]
@cescoffier thanks but still not working

I added the `@fliuent` annotation to the service like this

	@VertxGen
	@ProxyGen
	public interface ElasticSearchService {

		static ElasticSearchService createEventBusProxy(Vertx vertx, String address) {
			return ProxyHelper.createProxy(ElasticSearchService.class, vertx, address);
		}
		
		@Fluent
		ElasticSearchService getService();


but the return type is different

`com.englishtown.vertx.elasticsearch.ElasticSearchServiceVertxEBProxy cannot be cast to com.englishtown.vertx.elasticsearch.impl.DefaultElasticSearchService`

What I would like is to get an instance of `DefaultElasticSearchService` implementation of  ElasticSearchService and can call `getClient` method.

I'm not sure how I would do that...any ideas ?

**Comment by cescoffier** [comment]
You don't really choose the implementation. It's an "implementation detail" hidden behind the service. So the proxy cannot be casted to the service implementation, but used using the interface. 

If you look at the generated class, it does not extend your implementation.

**Comment by cescoffier** [comment]
please reopen if you think it's a bug.
