### ISSUE TITLE
Generated converters should support nested dataobjects

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-codegen#71]
Consider the following code:

``` java
@DataObject(generateConverter = true)
public class TopLevelOptions {
  private String top = "top";
  private NestedOptions nestedOptions = new NestedOptions();
...
}

@DataObject(generateConverter = true)
public class NestedOptions {
  private String nested = "nested"
}
```

Currently, codegen creates a `TopLevelOptionsConverter#toJson` which looks like:

``` java
  public static void toJson(TopLevelOptions obj, JsonObject json) {
    json.put("top", obj.getTop());
  }
```

So the the `NestedOptions` info is missing.

**Comment by vietj** [comment]
does your NestedOptions have a toJson() too ? it does not look like it does on the example.

**Comment by tsegismont** [comment]
NestedOptions doesn't have its own `#toJson` method, it is in the generated `NestedOptionsConverter`

**Comment by vietj** [comment]
could you open this issue rather in vertx-core ? that's where dataobject generator is.

**Comment by vietj** [comment]
the NestedOptions should have a toJson method that uses the NestedOptionsConverter.
