### ISSUE TITLE
Consider removing check for default constructor in DataObject

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-codegen#77]
As discussed on the forum [here](https://groups.google.com/forum/#!searchin/vertx/dataobject/vertx/Q4a8eGXHjs4/Y10lDx2pI0QJ) and [here](https://groups.google.com/forum/#!topic/vertx/tae09mqv7zc) the check for existence of a default constructor on a `@DataObject` may be removed.

There is value in this, since many data objects do not have sensible defaults to set, and may also be immutable.

**Comment by vietj** [comment]
could you make some research and find out if any existing language integration requires default constructor ?

**Comment by aschrijver** [comment]
I have been looking through the code, but I am unfamiliar with all the codegen magic (as it's called on the website :)), so I can't be sure. Working purely in Java myself.

**Comment by dano** [comment]
@vietj I checked through Ruby last night and didn't see anything. I'll try to find some time today or tomorrow to go through the others.

**Comment by vietj** [comment]
someone can try a version of codegen without this limitation

deploy this snapshot and see how other languages behaves when building it.

adding a data object with no no_arg ctor to the codegen TCK and have a method on DataObjectTCK#methodWithNoDefaultConstructorDataObject that takes this object as arg and implement this TCK in various languages would just be perfect.

**Comment by dano** [comment]
@vietj I've made the changes you suggested and successfully built:
lang-ruby
lang-js
lang-ceylon
service-proxy

My lang-groovy build failed, but it failed without this change, too, so it seems unrelated.

I was also able to build all of the above with the requirement for a copy constructor removed, and a DataObjectWithNoCopyConstructor TCK object/method added. Perhaps the requirement for both the default constructor *and* the copy constructor can be lifted?

**Comment by dano** [comment]
@vietj Actually, I may have spoke to soon on the copy constructor...at the very least the default constructor isn't used in any of the code generation.

**Comment by vietj** [comment]
it is requirement for default constructor, not copy constructor, so I'm not to understand here

**Comment by dano** [comment]
@vietj Classes annotated with @DataObject currently require a copy constructor as well as a default constructor.

**Comment by dano** [comment]
Ok, all the builds also work with the copy constructor requirement removed. So it seems to be safe to remove both requirements.

**Comment by aschrijver** [comment]
That would be cool, nice work!

**Comment by vietj** [comment]
have you extended the TCK to test these cases ?

**Comment by vietj** [comment]
I think copy constructor might be needed in some cases though : if someone wants to make a generic dataobject codec, he needs to be able to copy the object

**Comment by vietj** [comment]
so not sure we want to remove this

**Comment by vietj** [comment]
need to think about it :-)

**Comment by aschrijver** [comment]
I do not mind the copy constructor, it would just be a boon if it is optional, the default constructor is different though.

**Comment by vietj** [comment]
actually a generic data object serialization with event bus already exists in service proxies requiring a toJson() method, so I think we can remove requirement for copy constructor too. so a data object would be serializable only if it provides a toJson() method. the json arg ctor is still mandatory.

**Comment by vietj** [comment]
so what we need now is to have this TCK that shows that all language will work with a data object with just the json constructor in DataObjectTCK

**Comment by vietj** [comment]
and implement it in various languages

**Comment by aschrijver** [comment]
In the forum post I suggested adding a default codec to vertx-core for data objects based on this json serialization, so `send` and `publish` have native support. Would that be valuable / viable?

**Comment by dano** [comment]
@vietj I've tested all the languages using a TCK with just a JsonObject constructor, and they all work. I'll try to get a PR up this afternoon.

**Comment by vietj** [comment]
@dano have you implemented the usage of the TCK in each language ? i.e something like:

for JavaScript:

```
obj.methodWithOnlyJsonConstructorDataObject({"foo":"bar");
```

and the TCKImpl that does in codegen:

```
assertEquals(new JsonObjec().put("foo", "bar");
```

?

**Comment by dano** [comment]
@vietj Ah, I've added the method to DataObjectTCKImpl.java, and validated that all languages still generated their code properly, but I haven't added a test case to api_test.* that exercises the `methodWithOnlyJsonObjectConstructorDataObject`. I'll add those and confirm everything still works.

**Comment by dano** [comment]
Ok, I've added tests for Ceylon, JS, and Ruby for the JsonObject-only DataObject. Everything still passes. I didn't add Groovy tests, since that doesn't want to build for me. If needed I can try to figure out what's going on there and get a test added.

I've pushed all the code changes to github, please take a quick look:
https://github.com/vert-x3/vertx-codegen/compare/master...dano:json_only_constructor?expand=1
https://github.com/vert-x3/vertx-lang-js/compare/master...dano:json_only_constructor?expand=1
https://github.com/vert-x3/vertx-lang-ruby/compare/master...dano:json_only_constructor?expand=1
https://github.com/vert-x3/vertx-lang-ceylon/compare/master...dano:json_only_constructor?expand=1

If everything looks ok, I'll open PRs, assuming you actually want the lang tests pushed.

**Comment by vietj** [comment]
looks good to me, feel free to make all the PR when it's done.

**Comment by dano** [comment]
@vietj I've opened the PRs:
https://github.com/vert-x3/vertx-codegen/pull/78
https://github.com/vert-x3/vertx-lang-js/pull/48
https://github.com/vert-x3/vertx-lang-ruby/pull/15
https://github.com/vert-x3/vertx-lang-ceylon/pull/8

**Comment by vietj** [comment]
I merged the PR, however we are missing still for Groovy

**Comment by dano** [comment]
@vietj Here's the Groovy PR: https://github.com/vert-x3/vertx-lang-groovy/pull/32

**Comment by vietj** [comment]
thanks for the contribution!

**Comment by aschrijver** [comment]
Thanks, both of you!!
