### ISSUE TITLE
@DataObject annotation clarifications for abstract class and interfaces

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-codegen#79]
From the documentation it is unclear to me whether or not a `@DataObject` notation can be set on an interface.

The [JavaDoc](https://github.com/vert-x3/vertx-codegen/blob/master/src/main/java/io/vertx/codegen/annotations/DataObject.java) mentions:
```
/**
 * ...
 * A data object can be an interface or an abstract class to accomodate the api design. Data object can extend
 * other data objects.
 * ...
 */
```
But there is no reference to this in the documentation, nor can I find any use of @DataObject on an interface.

Is this at all supported, and if yes, how is the implementation class found?

Thanks.

**Comment by vietj** [comment]
only interfaces annotated with @VertxGen are allowed as parameters of methods of @VertxGen classes. 

I think we would remove the annotability of interfaces actually.

**Comment by aschrijver** [comment]
I am not using this in combination with `@VertxGen` but to have data objects as parameter in service interfaces and do `@ProxyGen'. In most cases the data objects are concrete classes, but in some occasions it would be nice to have the interface annotated as data object and pass a  compatible (i.e. having the json constructor) instance to it.

**Comment by vietj** [comment]
thing is that most of the time @ProxyGen are also @VertxGen interfaces

**Comment by aschrijver** [comment]
Yes, agreed. So concrete classes are the way to go, I guess.

**Comment by aschrijver** [comment]
Thanks!

**Comment by vietj** [comment]
Hi, thought about this : https://github.com/vert-x3/vertx-codegen/issues/80

would it allow you to fulfill your use case ?

**Comment by aschrijver** [comment]
I think that is a nice feature to have, though in my current use case I specifically needed it on an interface.
I have an existing library `vertx-jwt-codec` (that I'll probably open-source later on) that gives me an instance of a `Claims` interface that I would like to the data object. The implementation is in `impl.ClaimsImpl` and should not be in service interfaces.

**Comment by vietj** [comment]
it would work also on an interface.

**Comment by aschrijver** [comment]
Ah great, that would be really cool!

**Comment by pmlopes** [comment]
@aschrijver did you look at vertx-auth-jwt? we already have support for jwt since 3.0 with claim support too.

**Comment by aschrijver** [comment]
Yes, I did. But I needed a bit more than that. So I created a project that has both an encoder and decoder, a bit more more options to set + validate claims, add claim validators, and then a web handler (not part of project) that does not use the Bearer indicator on the header (it is not OAuth I am using).
