### ISSUE TITLE
CodeGenProcessor produces invalid Java source on Eclipse JDT

### ISSUE THREAD

**Issue by cstamas** [vert-x3/vertx-codegen#81]
When jdt compiler used (using takari-lifecycle, packaging takari-jar, compilerId jdt), the generated sources are invalid, the `package` declaration is twice present in source and naturally chokes the compilation.

Edited short snippet from generated code:
```
...
*/

package package org.cstamas.vertx.orientdb;

import org.cstamas.vertx.orientdb.GraphDatabaseService;
import io.vertx.core.eventbus.DeliveryOptions;
import io.vertx.core.Vertx;
import io.vertx.core.Future;
...
```

As you see, the line `package package org.cstamas.vertx.orientdb;` is wrong.

Reason:
As I debugged, it seems that problem lies in [ClassModel line 504](https://github.com/vert-x3/vertx-codegen/blob/9b30df8105c943ad93542acb046e9d87467e54d1/src/main/java/io/vertx/codegen/ClassModel.java#L504). The `toString()` method of JDT implementation `org.eclipse.jdt.internal.compiler.apt.model.ElementImpl` returns `package org.cstamas.vertx.orientdb` instead of expected `org.cstamas.vertx.orientdb`.

So, to make it work on javac but also on jdt compiler, it might be useful to add some check and _remove the `package ` prefix if present_. Manually verified, that IF one of the two `package` keywords are removed, the generated code is just fine.

Reproducer: repo at this hash, used `mvnDebug` w/ remote debugger
https://github.com/cstamas/vertx-orientdb/tree/6062a5b1544a7e1711f3f82a68585085f8742f0a

**Comment by cstamas** [comment]
JDT offending code source:
http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/4.2/org.eclipse.jdt/core/3.8.1/org/eclipse/jdt/internal/compiler/lookup/PackageBinding.java#294

**Comment by vietj** [comment]
can you show the codegen part that generates this ?

**Comment by cstamas** [comment]
WDYM "codegen part"?

**Comment by cstamas** [comment]
This is the iface:
https://github.com/cstamas/vertx-orientdb/blob/6062a5b1544a7e1711f3f82a68585085f8742f0a/vertx-orientdb/src/main/java/org/cstamas/vertx/orientdb/GraphDatabaseService.java

**Comment by cstamas** [comment]
Fixed with
e1740d0769e56c2a4482d9a3ce28767d05990e2a
cf92498d19d399baf3ebc73f2f2f4faf23b37d08
