### ISSUE TITLE
Javascript codegen is missing import

### ISSUE THREAD

**Issue by marcelalburg** [vert-x3/vertx-codegen#84]
Hello,

if you build you own data objects and generate a proxy/service from it, the generated javascript file is missing a import/definition.

you can see this p.e. here : https://github.com/englishtown/vertx-elasticsearch-service/blob/develop/src/main/resources/vertx-elasticsearch-service-js/elastic_search_admin_service.js

if you add in this example:

`var com = Packages.com;
`

it loads fine.

Thanks
Marcel

**Comment by vietj** [comment]
can you open this issue in the vertx-service-proxy project instead ? that's were JS is generated

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-service-proxy #48](https://github.com/vert-x3/vertx-service-proxy/issues/48) via [**ZenHub**](https://www.zenhub.com/)
