### ISSUE TITLE
Proxies Data object param cannot extend jsonifiable class

### ISSUE THREAD

**Issue by marcust** [vert-x3/vertx-codegen#85]
```
io.vertx.codegen.GenException: type com.hubrick.vertx.kafka.producer.model.StringKafkaMessage does not have a valid 'public JsonObject toJson()' method.
	at io.vertx.codegen.ProxyModel.checkParamType(ProxyModel.java:89)
	at io.vertx.codegen.ClassModel.getParams(ClassModel.java:869)
	at io.vertx.codegen.ClassModel.addMethod(ClassModel.java:727)
```

What the message actually means is `Found 2 possible toJson implementations` in my case, because we have an `abstract` base class for our `@DataObject`, apparently he catches both methods and that leads to the exception. 

I don't really get the semantics here or why all `super` methods are taken into consideration as well, but apparently that ignores `@Override`.

Used to work in 3.2.1.

**Comment by vietj** [comment]
can you provide a reproducer for this case please ?

**Comment by marcust** [comment]
https://github.com/hubrick/vertx-kafka-service, just update vert.x dependency to 3.3

**Comment by vietj** [comment]
would you mind to write a failing test case reproducing it for this codegen project? it would provide great help

**Comment by vietj** [comment]
thanks for the test

**Comment by vietj** [comment]
Would you mind to check this branch https://github.com/vert-x3/vertx-codegen/tree/proxies-dataobject-param-cannot-extend-jsonifiable-class ?

**Comment by marcust** [comment]
Works for me

**Comment by vietj** [comment]
@marcust have you signed the Eclipse CLA ?

**Comment by marcust** [comment]
Yes, I have. Is there any way I can link to that or what do you need?

**Comment by vietj** [comment]
no need to check - thanks for the reply
