### ISSUE TITLE
Register CodeGenProcessor with ServiceLoader

### ISSUE THREAD

**Issue by sdhays** [vert-x3/vertx-codegen#98]
By adding the CodeGenProcessor to the ServiceLoader registry (https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html), the -processor argument to the compiler can be avoided. Just need to add a META-INF/services/javax.annotation.processing.Processor file with io.vertx.codegen.CodeGenProcessor in it.

**Comment by vietj** [comment]
done but on a `processor` jar classifier.
